---
sidebar: sidebar 
permalink: trident-reference/tridentctl.html 
keywords: tridentctl, trident, kubernetes, commands, options, usage, flags 
summary: Trident へのシンプルなアクセスを提供するコマンドラインユーティリティである tridentctl の詳細を確認できます。 
---
= tridentctl コマンドとオプション
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
。 https://github.com/NetApp/trident/releases["Trident インストーラバンドル"^] コマンドラインユーティリティを搭載しています。 `tridentctl`Astra Tridentに簡単にアクセスできます。十分な権限を持つ Kubernetes ユーザは、このロールを使用して Astra Trident をインストールしたり、 Astra Trident ポッドが含まれるネームスペースを直接管理したりできます。



== 使用可能なコマンドとオプション

使用方法については、を実行してください `tridentctl --help`。

使用可能なコマンドとグローバルオプションは次のとおりです。

[listing]
----
Usage:
  tridentctl [command]
----
使用可能なコマンド：

* `create`：Astra Tridentにリソースを追加
* `delete`：Astra Tridentから1つ以上のリソースを削除
* `get`：Astra Tridentから1つ以上のリソースを入手
* `help`:任意のコマンドに関するヘルプ。
* `images`：Tridentが必要とするコンテナイメージを表で印刷
* `import`：既存のリソースをAstra Tridentにインポート
* `install`：Astra Tridentをインストール
* `logs`：Astra Tridentからログを印刷
* `send`：Astra Tridentからリソースを送信
* `uninstall`：TridentからAstraをアンインストール。
* `update`：Astra Tridentのリソースを変更
* `upgrade`：Astra Tridentのリソースをアップグレード
* `version`：Astra Tridentのバージョンを印刷


フラグ：

* ``-d, --debug`:デバッグ出力。
* ``-h, --help`:のヘルプ `tridentctl`。
* ``-n, --namespace string`: Astra Tridentのネームスペースの導入。
* ``-o, --output string`:出力形式。JSON の 1 つ | yaml | name | wide | ps （デフォルト）。
* ``-s, --server string`：Astra Trident RESTインターフェイスのアドレス/ポート。
+

CAUTION: Trident REST インターフェイスは、 127.0.0.1 （ IPv4 の場合）または [::1] （ IPv6 の場合）のみをリスンして処理するように設定できます。




CAUTION: Trident REST インターフェイスは、 127.0.0.1 （ IPv4 の場合）または [::1] （ IPv6 の場合）のみをリスンして処理するように設定できます。



== `create`

を実行します `create` Astra Tridentにリソースを追加するコマンド。

[listing]
----
Usage:
  tridentctl create [option]
----
使用可能なオプション：
`backend`：Astra Tridentにバックエンドを追加



== `delete`

を実行できます `delete` コマンドを使用して、Astra Tridentから1つ以上のリソースを削除します。

[listing]
----
Usage:
  tridentctl delete [option]
----
使用可能なオプション：

* `backend`：Tridentから1つ以上のストレージバックエンドを削除
* `snapshot`：Astra Tridentから1つ以上のボリュームSnapshotを削除
* `storageclass`：Astra Tridentから1つ以上のストレージクラスを削除
* `volume`：Astra Tridentから1つ以上のストレージボリュームを削除




== `get`

を実行できます `get` Astra Tridentから1つ以上のリソースを取得するためのコマンドです。

[listing]
----
Usage:
  tridentctl get [option]
----
使用可能なオプション：

* `backend`：Tridentから1つ以上のストレージバックエンドを取得
* `snapshot`：Astra Tridentから1つ以上のスナップショットを取得
* `storageclass`：Astra Tridentから1つ以上のストレージクラスを取得
* `volume`：Astra Tridentから1つ以上のボリュームを取得


`volume` フラグ：
* ``-h, --help`：ボリュームのヘルプ。
* `--parentOfSubordinate string`：クエリを下位のソースボリュームに制限します。
* `--subordinateOf string`:クエリをボリュームの下位に制限します。



== `images`

を実行できます `images` Astra Tridentが必要とするコンテナイメージの表を印刷するためのフラグ。

[listing]
----
Usage:
  tridentctl images [flags]
----
フラグ：
* ``-h, --help`: Help for images.
* ``-v ,--k8s-version string`：Kubernetesクラスタのセマンティックバージョン。



== `import volume`

を実行できます `import volume` コマンドを使用して、既存のボリュームをAstra Tridentにインポートします。

[listing]
----
Usage:
  tridentctl import volume <backendName> <volumeName> [flags]
----
エイリアス：
`volume, v`

フラグ：

* ``-f, --filename string`: YAMLまたはJSON PVCファイルへのパス。
* ``-h, --help`：ボリュームのヘルプ。
* ``--no-manage`：PV/PVCのみを作成します。ボリュームのライフサイクル管理を想定しないでください。




== `install`

を実行できます `install` Astra Tridentのインストールにフラグを付けます。

[listing]
----
Usage:
  tridentctl install [flags]
----
フラグ：

* `--autosupport-image string`：AutoSupportテレメトリ用のコンテナイメージ（デフォルトは「NetApp/Trident autosupport：<current-version>」）。
* `--autosupport-proxy string`：AutoSupport テレメトリを送信するプロキシのアドレス/ポート。
* `--enable-node-prep`：ノードに必要なパッケージをインストールします。
* `--generate-custom-yaml`:インストールを行わずにYAMLファイルを生成します。
* `-h, --help`:インストールのヘルプ。
* `--http-request-timeout`：TridentコントローラのREST APIのHTTP要求タイムアウトを上書きします（デフォルトは1m30秒）。
* `--image-registry string`:内部イメージレジストリのアドレス/ポート。
* `--k8s-timeout duration`：すべてのKubernetes処理のタイムアウト（デフォルトは3分0）。
* `--kubelet-dir string`: kubeletの内部状態のホストの場所(デフォルトは/var/lib/kubelet )
* `--log-format string`: Astra Tridentのログ形式(テキスト、JSON](デフォルトは「text」)。
* `--pv string`: Astra Tridentが使用するレガシーPVの名前は、存在しないことを確認します(デフォルトは"trident")。
* `--pvc string`：Astra Tridentで使用されている従来のPVCの名前。このPVCが存在しないことを確認します（デフォルトは「trident」）。
* `--silence-autosupport`：AutoSupport バンドルを自動的にネットアップに送信しない（デフォルトはtrue）。
* `--silent`:インストール中は、ほとんどの出力を無効にします。
* `--trident-image string`：インストールするAstra Tridentのイメージ
* `--use-custom-yaml`: setupディレクトリに存在する既存のYAMLファイルを使用します。
* `--use-ipv6`：Astra Tridentの通信にIPv6を使用




== `logs`

を実行できます `logs` Astra Tridentからログを印刷するためのフラグ。

[listing]
----
Usage:
  tridentctl logs [flags]
----
フラグ：

* ``-a, --archive`：特に指定がないかぎり、すべてのログを含むサポートアーカイブを作成します。
* ``-h, --help`:ログのヘルプ。
* ``-l, --log string`：Astra Tridentのログが表示されます。trident | auto | trident-operator | all （デフォルトは「 auto 」）のいずれかです。
* ``--node string`：ノードポッドログの収集元のKubernetesノード名。
* ``-p, --previous`:以前のコンテナインスタンスのログが存在する場合は、それを取得します。
* ``--sidecars`:サイドカーコンテナのログを取得します。




== `send`

を実行できます `send` Astra Tridentからリソースを送信するコマンド。

[listing]
----
Usage:
  tridentctl send [option]
----
使用可能なオプション：
`autosupport`：ネットアップにAutoSupport アーカイブを送信します。



== `uninstall`

を実行できます `uninstall` Astra Tridentをアンインストールするためのフラグ。

[listing]
----
Usage:
  tridentctl uninstall [flags]
----
フラグ：
* `-h, --help`:アンインストールのヘルプ。
* `--silent`:アンインストール中のほとんどの出力を無効にします。



== `update`

を実行できます `update` Astra Tridentのリソースを変更するコマンド。

[listing]
----
Usage:
  tridentctl update [option]
----
使用可能なオプション：
`backend`：Astra Tridentのバックエンドを更新。



== `version`

を実行できます `version` のバージョンを印刷するためのフラグ `tridentctl` 実行中のTridentサービス

[listing]
----
Usage:
  tridentctl version [flags]
----
フラグ：
* `--client`:クライアントバージョンのみ(サーバは不要)。
* `-h, --help`:バージョンのヘルプ。
